/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisasRouteImport } from './routes/visas'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PickupsRouteImport } from './routes/pickups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VisasBookRouteImport } from './routes/visas.book'
import { Route as ToursBookRouteImport } from './routes/tours.book'
import { Route as StaysBookRouteImport } from './routes/stays.book'
import { Route as PickupsBookRouteImport } from './routes/pickups.book'
import { Route as InsuranceBookRouteImport } from './routes/insurance.book'
import { Route as FlightsBookRouteImport } from './routes/flights.book'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardConsultationsRouteImport } from './routes/dashboard.consultations'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardBookRouteImport } from './routes/dashboard.book'
import { Route as AgentsApplyRouteImport } from './routes/agents.apply'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminMarkupsRouteImport } from './routes/admin.markups'
import { Route as AdminCurrenciesRouteImport } from './routes/admin.currencies'
import { Route as AdminConsultationsRouteImport } from './routes/admin.consultations'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminApiProvidersRouteImport } from './routes/admin.api-providers'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'

const VisasRoute = VisasRouteImport.update({
  id: '/visas',
  path: '/visas',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupsRoute = PickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VisasBookRoute = VisasBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => VisasRoute,
} as any)
const ToursBookRoute = ToursBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ToursRoute,
} as any)
const StaysBookRoute = StaysBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => StaysRoute,
} as any)
const PickupsBookRoute = PickupsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PickupsRoute,
} as any)
const InsuranceBookRoute = InsuranceBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => InsuranceRoute,
} as any)
const FlightsBookRoute = FlightsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => FlightsRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConsultationsRoute = DashboardConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookRoute = DashboardBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => DashboardRoute,
} as any)
const AgentsApplyRoute = AgentsApplyRouteImport.update({
  id: '/agents/apply',
  path: '/agents/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarkupsRoute = AdminMarkupsRouteImport.update({
  id: '/markups',
  path: '/markups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiProvidersRoute = AdminApiProvidersRouteImport.update({
  id: '/api-providers',
  path: '/api-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/flights': typeof FlightsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance': typeof InsuranceRouteWithChildren
  '/login': typeof LoginRoute
  '/pickups': typeof PickupsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRouteWithChildren
  '/tours': typeof ToursRouteWithChildren
  '/visas': typeof VisasRouteWithChildren
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/api-providers': typeof AdminApiProvidersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/markups': typeof AdminMarkupsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/agents/apply': typeof AgentsApplyRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/flights/book': typeof FlightsBookRoute
  '/insurance/book': typeof InsuranceBookRoute
  '/pickups/book': typeof PickupsBookRoute
  '/stays/book': typeof StaysBookRoute
  '/tours/book': typeof ToursBookRoute
  '/visas/book': typeof VisasBookRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultations': typeof ConsultationsRoute
  '/flights': typeof FlightsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance': typeof InsuranceRouteWithChildren
  '/login': typeof LoginRoute
  '/pickups': typeof PickupsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRouteWithChildren
  '/tours': typeof ToursRouteWithChildren
  '/visas': typeof VisasRouteWithChildren
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/api-providers': typeof AdminApiProvidersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/markups': typeof AdminMarkupsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/agents/apply': typeof AgentsApplyRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/flights/book': typeof FlightsBookRoute
  '/insurance/book': typeof InsuranceBookRoute
  '/pickups/book': typeof PickupsBookRoute
  '/stays/book': typeof StaysBookRoute
  '/tours/book': typeof ToursBookRoute
  '/visas/book': typeof VisasBookRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultations': typeof ConsultationsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/flights': typeof FlightsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance': typeof InsuranceRouteWithChildren
  '/login': typeof LoginRoute
  '/pickups': typeof PickupsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRouteWithChildren
  '/tours': typeof ToursRouteWithChildren
  '/visas': typeof VisasRouteWithChildren
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/api-providers': typeof AdminApiProvidersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/markups': typeof AdminMarkupsRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/agents/apply': typeof AgentsApplyRoute
  '/dashboard/book': typeof DashboardBookRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/flights/book': typeof FlightsBookRoute
  '/insurance/book': typeof InsuranceBookRoute
  '/pickups/book': typeof PickupsBookRoute
  '/stays/book': typeof StaysBookRoute
  '/tours/book': typeof ToursBookRoute
  '/visas/book': typeof VisasBookRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consultations'
    | '/dashboard'
    | '/flights'
    | '/forgot-password'
    | '/insurance'
    | '/login'
    | '/pickups'
    | '/reset-password'
    | '/signup'
    | '/stays'
    | '/tours'
    | '/visas'
    | '/admin/agents'
    | '/admin/api-providers'
    | '/admin/bookings'
    | '/admin/consultations'
    | '/admin/currencies'
    | '/admin/markups'
    | '/admin/operations'
    | '/admin/users'
    | '/admin/wallets'
    | '/agents/apply'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/consultations'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/flights/book'
    | '/insurance/book'
    | '/pickups/book'
    | '/stays/book'
    | '/tours/book'
    | '/visas/book'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultations'
    | '/flights'
    | '/forgot-password'
    | '/insurance'
    | '/login'
    | '/pickups'
    | '/reset-password'
    | '/signup'
    | '/stays'
    | '/tours'
    | '/visas'
    | '/admin/agents'
    | '/admin/api-providers'
    | '/admin/bookings'
    | '/admin/consultations'
    | '/admin/currencies'
    | '/admin/markups'
    | '/admin/operations'
    | '/admin/users'
    | '/admin/wallets'
    | '/agents/apply'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/consultations'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/flights/book'
    | '/insurance/book'
    | '/pickups/book'
    | '/stays/book'
    | '/tours/book'
    | '/visas/book'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consultations'
    | '/dashboard'
    | '/flights'
    | '/forgot-password'
    | '/insurance'
    | '/login'
    | '/pickups'
    | '/reset-password'
    | '/signup'
    | '/stays'
    | '/tours'
    | '/visas'
    | '/admin/agents'
    | '/admin/api-providers'
    | '/admin/bookings'
    | '/admin/consultations'
    | '/admin/currencies'
    | '/admin/markups'
    | '/admin/operations'
    | '/admin/users'
    | '/admin/wallets'
    | '/agents/apply'
    | '/dashboard/book'
    | '/dashboard/bookings'
    | '/dashboard/consultations'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/flights/book'
    | '/insurance/book'
    | '/pickups/book'
    | '/stays/book'
    | '/tours/book'
    | '/visas/book'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsultationsRoute: typeof ConsultationsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FlightsRoute: typeof FlightsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsuranceRoute: typeof InsuranceRouteWithChildren
  LoginRoute: typeof LoginRoute
  PickupsRoute: typeof PickupsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StaysRoute: typeof StaysRouteWithChildren
  ToursRoute: typeof ToursRouteWithChildren
  VisasRoute: typeof VisasRouteWithChildren
  AgentsApplyRoute: typeof AgentsApplyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visas': {
      id: '/visas'
      path: '/visas'
      fullPath: '/visas'
      preLoaderRoute: typeof VisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickups': {
      id: '/pickups'
      path: '/pickups'
      fullPath: '/pickups'
      preLoaderRoute: typeof PickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/visas/book': {
      id: '/visas/book'
      path: '/book'
      fullPath: '/visas/book'
      preLoaderRoute: typeof VisasBookRouteImport
      parentRoute: typeof VisasRoute
    }
    '/tours/book': {
      id: '/tours/book'
      path: '/book'
      fullPath: '/tours/book'
      preLoaderRoute: typeof ToursBookRouteImport
      parentRoute: typeof ToursRoute
    }
    '/stays/book': {
      id: '/stays/book'
      path: '/book'
      fullPath: '/stays/book'
      preLoaderRoute: typeof StaysBookRouteImport
      parentRoute: typeof StaysRoute
    }
    '/pickups/book': {
      id: '/pickups/book'
      path: '/book'
      fullPath: '/pickups/book'
      preLoaderRoute: typeof PickupsBookRouteImport
      parentRoute: typeof PickupsRoute
    }
    '/insurance/book': {
      id: '/insurance/book'
      path: '/book'
      fullPath: '/insurance/book'
      preLoaderRoute: typeof InsuranceBookRouteImport
      parentRoute: typeof InsuranceRoute
    }
    '/flights/book': {
      id: '/flights/book'
      path: '/book'
      fullPath: '/flights/book'
      preLoaderRoute: typeof FlightsBookRouteImport
      parentRoute: typeof FlightsRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/consultations': {
      id: '/dashboard/consultations'
      path: '/consultations'
      fullPath: '/dashboard/consultations'
      preLoaderRoute: typeof DashboardConsultationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/book': {
      id: '/dashboard/book'
      path: '/book'
      fullPath: '/dashboard/book'
      preLoaderRoute: typeof DashboardBookRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/agents/apply': {
      id: '/agents/apply'
      path: '/agents/apply'
      fullPath: '/agents/apply'
      preLoaderRoute: typeof AgentsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/markups': {
      id: '/admin/markups'
      path: '/markups'
      fullPath: '/admin/markups'
      preLoaderRoute: typeof AdminMarkupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-providers': {
      id: '/admin/api-providers'
      path: '/api-providers'
      fullPath: '/admin/api-providers'
      preLoaderRoute: typeof AdminApiProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminApiProvidersRoute: typeof AdminApiProvidersRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminMarkupsRoute: typeof AdminMarkupsRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminApiProvidersRoute: AdminApiProvidersRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminConsultationsRoute: AdminConsultationsRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminMarkupsRoute: AdminMarkupsRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBookRoute: typeof DashboardBookRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardConsultationsRoute: typeof DashboardConsultationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBookRoute: DashboardBookRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardConsultationsRoute: DashboardConsultationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FlightsRouteChildren {
  FlightsBookRoute: typeof FlightsBookRoute
}

const FlightsRouteChildren: FlightsRouteChildren = {
  FlightsBookRoute: FlightsBookRoute,
}

const FlightsRouteWithChildren =
  FlightsRoute._addFileChildren(FlightsRouteChildren)

interface InsuranceRouteChildren {
  InsuranceBookRoute: typeof InsuranceBookRoute
}

const InsuranceRouteChildren: InsuranceRouteChildren = {
  InsuranceBookRoute: InsuranceBookRoute,
}

const InsuranceRouteWithChildren = InsuranceRoute._addFileChildren(
  InsuranceRouteChildren,
)

interface PickupsRouteChildren {
  PickupsBookRoute: typeof PickupsBookRoute
}

const PickupsRouteChildren: PickupsRouteChildren = {
  PickupsBookRoute: PickupsBookRoute,
}

const PickupsRouteWithChildren =
  PickupsRoute._addFileChildren(PickupsRouteChildren)

interface StaysRouteChildren {
  StaysBookRoute: typeof StaysBookRoute
}

const StaysRouteChildren: StaysRouteChildren = {
  StaysBookRoute: StaysBookRoute,
}

const StaysRouteWithChildren = StaysRoute._addFileChildren(StaysRouteChildren)

interface ToursRouteChildren {
  ToursBookRoute: typeof ToursBookRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursBookRoute: ToursBookRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

interface VisasRouteChildren {
  VisasBookRoute: typeof VisasBookRoute
}

const VisasRouteChildren: VisasRouteChildren = {
  VisasBookRoute: VisasBookRoute,
}

const VisasRouteWithChildren = VisasRoute._addFileChildren(VisasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsultationsRoute: ConsultationsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FlightsRoute: FlightsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsuranceRoute: InsuranceRouteWithChildren,
  LoginRoute: LoginRoute,
  PickupsRoute: PickupsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StaysRoute: StaysRouteWithChildren,
  ToursRoute: ToursRouteWithChildren,
  VisasRoute: VisasRouteWithChildren,
  AgentsApplyRoute: AgentsApplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
